# My variables
name: danishprakash
description: ~

# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]


# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Google analytics tracking ID
google_analytics: "UA-101783497-1"

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
